name: .NET
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
 
  test:
    runs-on: ubuntu-latest
    needs: build
 
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
 
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: staging
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Configure Git
      run: |
        git config --local user.email "ruitersbrooklyn@gmail.com"
        git config --local user.name "brookbal"
    - name: Commit and push to staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout -b stage || git checkout stage
        git add .
        git commit -m "Deploying to staging" || echo "No changes to commit"
        git push origin stage
